sudo: required

services:
    - docker

# before_install:
#     - docker pull harshjv/texlive-2015
#     - docker build -t texlive docker

script:
    - docker run --rm harshjv/texlive-2015 ls -lah /opt/texbin/
    - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 pdflatex main.tex
    - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 ls -lah /opt/texbin/

